language: php

php:
  - 7.1
matrix:
  fast_finish: true

cache:
  directories:
    - $COMPOSER_CACHE_DIR

install:
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - mkdir -p build/logs
  - ./bin/phpunit
